[project]
name = "lumi"
version = "0.1.0"
description = "Speech-to-text utility with hotkey activation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "groq>=0.18.0",
    "pyaudio>=0.2.14",
    "pygame>=2.6.1",
    "pynput>=1.7.7",
    "pyperclip>=1.9.0",
    "pytest>=8.3.4",
    "requests>=2.32.3",
    "ruff>=0.9.8",
]

[project.scripts]
lumi = "lumi.cli.s2t_cli:main"

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["lumi"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
